// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrGyYxvOj_ebWUnIh--gjGPmgAA4dJ7ug',
    appId: '1:179709926400:web:8f5f5e8cdc8ef6f6678ce5',
    messagingSenderId: '179709926400',
    projectId: 'chatapptute-27940',
    authDomain: 'chatapptute-27940.firebaseapp.com',
    storageBucket: 'chatapptute-27940.firebasestorage.app',
    measurementId: 'G-N00MLXJCTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrSW9WG1tmQtTkyptDT2FDEZpmx9Ka9xg',
    appId: '1:179709926400:android:8221bbacba527deb678ce5',
    messagingSenderId: '179709926400',
    projectId: 'chatapptute-27940',
    storageBucket: 'chatapptute-27940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFj6y51w9o4JIcoesiOH7c8FlFgzC7mm8',
    appId: '1:179709926400:ios:722f23437b814606678ce5',
    messagingSenderId: '179709926400',
    projectId: 'chatapptute-27940',
    storageBucket: 'chatapptute-27940.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
